# Source: sd-core/charts/5g-control-plane/templates/configmap-udr.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: udr
  labels:
    release: sd-core
    app: udr
  namespace: omec
data:
  udr-run.sh: |
    #!/bin/sh

    # Copyright 2020-present Open Networking Foundation
    #
    # SPDX-License-Identifier: Apache-2.0

    set -xe

    cd /free5gc

    cat config/udrcfg.conf

    GOTRACEBACK=crash ./udr/udr -udrcfg config/udrcfg.conf
  udrcfg.conf: |-
    configuration:
      mongodb:
        name: free5gc
        url: mongodb://mongodb
      nrfUri: http://nrf:29510
      plmnSupportList:
      - plmnId:
          mcc: "208"
          mnc: "93"
      - plmnId:
          mcc: "333"
          mnc: "88"
      sbi:
        bindingIPv4: 0.0.0.0
        port: 29504
        registerIPv4: udr
        scheme: http
    info:
      description: UDR initial local configuration
      version: 1.0.0
    logger:
      AMF:
        ReportCaller: false
        debugLevel: info
      AUSF:
        ReportCaller: false
        debugLevel: info
      Aper:
        ReportCaller: false
        debugLevel: info
      CommonConsumerTest:
        ReportCaller: false
        debugLevel: info
      FSM:
        ReportCaller: false
        debugLevel: info
      MongoDBLibrary:
        ReportCaller: false
        debugLevel: info
      N3IWF:
        ReportCaller: false
        debugLevel: info
      NAS:
        ReportCaller: false
        debugLevel: info
      NGAP:
        ReportCaller: false
        debugLevel: info
      NRF:
        ReportCaller: false
        debugLevel: info
      NamfComm:
        ReportCaller: false
        debugLevel: info
      NamfEventExposure:
        ReportCaller: false
        debugLevel: info
      NsmfPDUSession:
        ReportCaller: false
        debugLevel: info
      NudrDataRepository:
        ReportCaller: false
        debugLevel: info
      OpenApi:
        ReportCaller: false
        debugLevel: info
      PCF:
        ReportCaller: false
        debugLevel: info
      PFCP:
        ReportCaller: false
        debugLevel: info
      PathUtil:
        ReportCaller: false
        debugLevel: info
      SMF:
        ReportCaller: false
        debugLevel: info
      UDM:
        ReportCaller: false
        debugLevel: info
      UDR:
        ReportCaller: false
        debugLevel: info
      WEBUI:
        ReportCaller: false
        debugLevel: info
