# Source: sd-core/charts/omec-sub-provision/templates/configmap-simapp.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: simapp
  labels:
    release: sd-core
    app: simapp
  namespace: omec
data:
  simapp-run.sh: |
    #!/bin/sh

    # Copyright 2020-present Open Networking Foundation
    #
    # SPDX-License-Identifier: Apache-2.0

    set -xe

    cd /simapp
    cat config/simapp.yaml

    ./bin/simapp -simapp config/simapp.yaml
  simapp.yaml: |-
    configuration:
      device-groups:
      - imsis:
        - "001010000000106"
        ip-domain-expanded:
          dnn: internet
          dns-primary: 8.8.8.8
          mtu: 1460
          ue-dnn-qos:
            bitrate-unit: bps
            dnn-mbr-downlink: 2000000000
            dnn-mbr-uplink: 1000000000
            traffic-class:
              arp: 6
              name: platinum
              pdb: 300
              pelr: 6
              qci: 9
          ue-ip-pool: 172.250.0.0/16
        ip-domain-name: pool1
        name: 5g-gnbsim-user
        site-info: aiab
      network-slices:
      - application-filtering-rules:
        - action: permit
          endpoint: 0.0.0.0/0
          priority: 250
          rule-name: ALLOW-ALL
        name: default
        site-device-group:
        - 5g-gnbsim-user
        site-info:
          gNodeBs:
          - name: aiab-gnb1
            tac: 1
          plmn:
            mcc: "001"
            mnc: "01"
          site-name: aiab
          upf:
            upf-name: upf
            upf-port: 8805
        slice-id:
          sd: "010203"
          sst: 1
      provision-network-slice: true
      sub-provision-endpt:
        addr: webui.omec.svc.cluster.local
        port: 5000
      subscribers:
      - key: 00112233445566778899AABBCCDDEEFF
        op: ""
        opc: 279EB54971771559879284FDDDE3EE0C
        plmnId: "00101"
        sequenceNumber: 16f3b3f70fc2
        ueId-end: "001010000000106"
        ueId-start: "001010000000106"
    info:
      description: SIMAPP initial local configuration
      http-version: 1
      version: 1.0.0
    logger:
      APP:
        ReportCaller: false
        debugLevel: info
