# Source: sd-core/charts/omec-sub-provision/templates/deployment-simapp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simapp
  labels:
    release: sd-core
    app: simapp
  namespace: omec
spec:
  replicas: 1
  #serviceName: simapp-headless
  selector:
    matchLabels:
      release: sd-core
      app: simapp
  template:
    metadata:
      labels:
        release: sd-core
        app: simapp
      annotations:
        helm.sh/hook: pre-install
        helm.sh/hook-weight: "5"
        field.cattle.io/workloadMetrics: '[{"path":"/metrics","port":9089,"schema":"HTTP"}]'
    spec:
      serviceAccountName: simapp
      initContainers:
      - name: wait-simapp-module2
        image: registry.opennetworking.org/docker.io/omecproject/pod-init:1.0.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup simapp; do echo waiting for simapp; sleep 4; done;']
      containers:
      - name: simapp
        image: registry.opennetworking.org/docker.io/omecproject/simapp:main-a4f741a
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        command: ["/simapp/script/simapp-run.sh"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: run-script
          mountPath: /simapp/script/simapp-run.sh
          subPath: simapp-run.sh
        - name: nf-config
          mountPath: /simapp/config
      volumes:
      - name: run-script
        configMap:
          name: simapp
          defaultMode: 493
      - name: nf-config
        configMap:
          name: simapp
          defaultMode: 493
