# Source: sd-core/charts/5g-control-plane/templates/deployment-ausf.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
  labels:
    release: sd-core
    app: ausf
  namespace: omec
spec:
  replicas: 1
  #serviceName: ausf-headless
  selector:
    matchLabels:
      release: sd-core
      app: ausf
  template:
    metadata:
      labels:
        release: sd-core
        app: ausf
    spec:
      serviceAccountName: ausf
      initContainers:
      - name: wait-ausf-module2
        image: registry.opennetworking.org/docker.io/omecproject/pod-init:1.0.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup ausf; do echo waiting for ausf; sleep 4; done;']
      containers:
      - name: ausf
        image: registry.opennetworking.org/docker.io/omecproject/5gc-ausf:master-1890449
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        command: ["/free5gc/script/ausf-run.sh"]
        env:
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        - name: GRPC_TRACE
          value: "all"
        - name: GRPC_VERBOSITY
          value: "debug"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MANAGED_BY_CONFIG_POD
          value: "true"
        volumeMounts:
        - name: run-script
          mountPath: /free5gc/script/ausf-run.sh
          subPath: ausf-run.sh
        - name: nf-config
          mountPath: /free5gc/config
      volumes:
      - name: run-script
        configMap:
          name: ausf
          defaultMode: 493
      - name: nf-config
        configMap:
          name: ausf
          defaultMode: 493
