# Source: sd-core/charts/5g-control-plane/templates/service-nrf.yaml
apiVersion: v1
kind: Service
metadata:
  name: nrf
  labels:
    release: sd-core
    app: nrf
  namespace: omec
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: nrf
  ports:
  - name: sbi
    port: 29510
    protocol: TCP
