# Source: sd-core/charts/5g-control-plane/templates/service-webui.yaml
apiVersion: v1
kind: Service
metadata:
  name: webui
  labels:
    release: sd-core
    app: webui
  namespace: omec
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: webui
  ports:
  - name: urlport-http
    port: 5000
    protocol: TCP
  - name: grpc
    port: 9876
    protocol: TCP
