# Source: sd-core/charts/5g-control-plane/templates/service-udr.yaml
apiVersion: v1
kind: Service
metadata:
  name: udr
  labels:
    release: sd-core
    app: udr
  namespace: omec
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: udr
  ports:
  - name: sbi
    port: 29504
    protocol: TCP
