# Source: sd-core/charts/5g-control-plane/templates/service-ausf.yaml
apiVersion: v1
kind: Service
metadata:
  name: ausf
  labels:
    release: sd-core
    app: ausf
  namespace: omec
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: ausf
  ports:
  - name: sbi
    port: 29509
    protocol: TCP
