# Source: sd-core/charts/5g-control-plane/templates/service-pcf.yaml
apiVersion: v1
kind: Service
metadata:
  name: pcf
  labels:
    release: sd-core
    app: pcf
  namespace: omec
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: pcf
  ports:
  - name: sbi
    port: 29507
    protocol: TCP
