# Source: sd-core/charts/5g-control-plane/templates/deployment-udr.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: udr
  namespace: omec
  labels:
    release: sd-core
    app: udr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: udr
subjects:
- kind: ServiceAccount
  name: udr
  namespace: omec
