# Source: sd-core/charts/5g-control-plane/templates/deployment-pcf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pcf
  namespace: default
  labels:
    release: sd-core
    app: pcf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pcf
subjects:
- kind: ServiceAccount
  name: pcf
  namespace: default
