# Source: sd-core/charts/5g-control-plane/templates/deployment-smf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smf
  namespace: default
  labels:
    release: sd-core
    app: smf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: smf
subjects:
- kind: ServiceAccount
  name: smf
  namespace: default
