# Source: sd-core/charts/5g-control-plane/templates/deployment-udm.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: udm
  namespace: default
  labels:
    release: sd-core
    app: udm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: udm
subjects:
- kind: ServiceAccount
  name: udm
  namespace: default
