apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: subscriber-proxy-secret-reader
  namespace: default
subjects:
- kind: ServiceAccount
  name: subscriber-proxy
  namespace: default
roleRef:
  kind: ClusterRole
  name: subscriber-proxy-secret-reader-role
  apiGroup: rbac.authorization.k8s.io
