# Source: aether-roc-umbrella/charts/grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-roc-umbrella-grafana
  namespace: default
  labels:
    helm.sh/chart: grafana-6.16.6
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/version: "8.1.2"
    app.kubernetes.io/managed-by: Helm
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth]
    disable_login_form = true
    oauth_auto_login = true
    [auth.anonymous]
    enabled = false
    hide_version = false
    [auth.generic_oauth]
    allow_sign_up = true
    allowed_domains = opennetworking.org
    api_url = http://k3u-keycloak:5557/auth/realms/master/protocol/openid-connect/userinfo
    auth_url = http://k3u-keycloak:5557/auth/realms/master/protocol/openid-connect/auth
    client_id = aether-roc-gui
    empty_scopes = false
    enabled = true
    name = KeyCloak
    scopes = openid profile email groups
    token_url = http://k3u-keycloak:5557/auth/realms/master/protocol/openid-connect/token
    [auth.jwt]
    cache_ttl = 60m
    email_claim = email
    enabled = false
    header_name = X-JWT-Assertion
    jwk_set_url = https://keycloak.opennetworking.org/auth/realms/master/protocol/openid-connect/certs
    username_claim = name
    [auth.proxy]
    auto_sign_up = true
    enable_login_token = true
    enabled = false
    header_name = X-WEBAUTH-USER
    header_property = username
    [grafana_net]
    url = https://grafana.net
    [log]
    level = debug
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [security]
    allow_embedding = true
    [server]
    domain = aether-roc-gui:8183
    root_url = %(protocol)s://%(domain)s/grafana/
    serve_from_sub_path = true
