apiVersion: apps/v1
kind: Deployment
metadata:
  name: aether-roc-umbrella-sdcore-prom-kafka
  namespace: default
  labels:
    name: aether-roc-umbrella-sdcore-prom-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sdcore-prom-kafka
      app.kubernetes.io/instance: aether-roc-umbrella
  template:
    metadata:
      labels:
        name: aether-roc-umbrella-sdcore-prom-kafka
        app.kubernetes.io/name: sdcore-prom-kafka
        app.kubernetes.io/instance: aether-roc-umbrella
    spec:
      securityContext: null
      containers:
      - name: sdcore-prom-kafka
        image: "onosproject/sdcore-adapter:v0.4.4"
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - "/usr/local/bin/sdcore-kafka"
        - "-kafka_uri=kafka-0.kafka-headless:9092"
        - "-endpoint=http://aether-roc-umbrella-prometheus-acc-server:80"
        volumeMounts:
        - name: logconfig
          mountPath: /etc/onos/config
          readOnly: true
      volumes:
      - name: logconfig
        configMap:
          name: aether-roc-umbrella-sdcore-prom-kafka-logconfig
