# Source: aether-roc-umbrella/charts/prometheus-amp/templates/server/deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: "server"
    app: prometheus-amp
    release: aether-roc-umbrella
    chart: prometheus-amp-14.6.1
    heritage: Helm
  name: aether-roc-umbrella-prometheus-amp-server
  namespace: default
spec:
  selector:
    matchLabels:
      component: "server"
      app: prometheus-amp
      release: aether-roc-umbrella
  replicas: 1
  template:
    metadata:
      labels:
        component: "server"
        app: prometheus-amp
        release: aether-roc-umbrella
        chart: prometheus-amp-14.6.1
        heritage: Helm
    spec:
      enableServiceLinks: true
      serviceAccountName: aether-roc-umbrella-prometheus-amp-server
      containers:
      - name: prometheus-amp-server-configmap-reload
        image: "jimmidyson/configmap-reload:v0.5.0"
        imagePullPolicy: "IfNotPresent"
        args:
        - --volume-dir=/etc/config
        - --webhook-url=http://127.0.0.1:9090/-/reload
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
      - name: prometheus-amp-server
        image: "quay.io/prometheus/prometheus:v2.26.0"
        imagePullPolicy: "IfNotPresent"
        args:
        - --storage.tsdb.retention.time=15d
        - --config.file=/etc/config/prometheus.yml
        - --storage.tsdb.path=/data
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --web.enable-lifecycle
        ports:
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 4
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: storage-volume
          mountPath: /data
          subPath: ""
      hostNetwork: false
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      terminationGracePeriodSeconds: 300
      volumes:
      - name: config-volume
        configMap:
          name: aether-roc-umbrella-prometheus-amp-server
      - name: storage-volume
        emptyDir: {}
