apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-label-proxy-acc
  namespace: default
  labels:
    name: prom-label-proxy-acc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prom-label-proxy-acc
      app.kubernetes.io/instance: aether-roc-umbrella
  template:
    metadata:
      labels:
        name: prom-label-proxy-acc
        app.kubernetes.io/name: prom-label-proxy-acc
        app.kubernetes.io/instance: aether-roc-umbrella
    spec:
      securityContext: null
      containers:
      - name: prom-label-proxy-acc
        image: "onosproject/prom-label-proxy:v0.3.6"
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OIDC_SERVER_URL
          value:
        args: ["-label=ent", "-admingroup=AetherROCAdmin", "-upstream=http://aether-roc-umbrella-prometheus-acc-server", "-insecure-listen-address=0.0.0.0:8080", "-config_address=$(POD_IP):5150", "-onos_config_url=onos-config:5150", "-key=/etc/prom-label-proxy/certs/tls.key", "-cert=/etc/prom-label-proxy/certs/tls.crt", "-ca=/etc/prom-label-proxy/certs/tls.cacert"]
        ports:
        - name: http
          containerPort: 8080
        - name: gnmi
          containerPort: 5150
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: secret
          mountPath: /etc/prom-label-proxy/certs
          readOnly: true
      volumes:
      - name: secret
        secret:
          secretName: prom-label-proxy-acc-secret
