# Source: aether-roc-umbrella/charts/onos-config/templates/primitives.yaml
apiVersion: primitives.atomix.io/v2beta1
kind: IndexedMap
metadata:
  name: onos-config-network-changes
  namespace: default
spec:
  store:
    name: onos-consensus-store
