# Source: aether-roc-umbrella/charts/grafana/templates/tests/test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: aether-roc-umbrella-grafana-test
  labels:
    helm.sh/chart: grafana-6.16.6
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/version: "8.1.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
  namespace: default
spec:
  serviceAccountName: aether-roc-umbrella-grafana-test
  containers:
  - name: aether-roc-umbrella-test
    image: "bats/bats:v1.1.0"
    imagePullPolicy: "IfNotPresent"
    command: ["/opt/bats/bin/bats", "-t", "/tests/run.sh"]
    volumeMounts:
    - mountPath: /tests
      name: tests
      readOnly: true
  volumes:
  - name: tests
    configMap:
      name: aether-roc-umbrella-grafana-test
  restartPolicy: Never
