kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onos-config
  namespace: default
subjects:
- kind: ServiceAccount
  name: onos-config
roleRef:
  kind: Role
  name: onos-config
  apiGroup: rbac.authorization.k8s.io
