apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aether-roc-gui-v2-1-access-services
  namespace: default
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive
  namespace: default
roleRef:
  kind: Role
  name: aether-roc-gui-v2-1-service-role
  apiGroup: rbac.authorization.k8s.io
