# Source: aether-roc-umbrella/charts/prometheus-amp/templates/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    component: "server"
    app: prometheus-amp
    release: aether-roc-umbrella
    chart: prometheus-amp-14.6.1
    heritage: Helm
  name: aether-roc-umbrella-prometheus-amp-server
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    component: "server"
    app: prometheus-amp
    release: aether-roc-umbrella
  sessionAffinity: None
  type: "ClusterIP"
