# Source: aether-roc-umbrella/charts/grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: grafana-6.16.6
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/version: "8.1.2"
    app.kubernetes.io/managed-by: Helm
  name: aether-roc-umbrella-grafana
  namespace: default
