# Source: aether-roc-umbrella/charts/prometheus-acc/templates/server/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    component: "server"
    app: prometheus-acc
    release: aether-roc-umbrella
    chart: prometheus-acc-14.6.1
    heritage: Helm
  name: aether-roc-umbrella-prometheus-acc-server
subjects:
- kind: ServiceAccount
  name: aether-roc-umbrella-prometheus-acc-server
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aether-roc-umbrella-prometheus-acc-server
