apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-roc-umbrella-sdcore-prom-kafka-logconfig
  labels:
    app: aether-roc-umbrella-sdcore-prom-kafka
    chart: "sdcore-prom-kafka-1.0.0"
    release: "aether-roc-umbrella"
    heritage: "Helm"
data:
  logging.yaml: |-
    loggers:
      root:
        level: info
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        stdout: {}
        type: stdout
