# Source: aether-roc-umbrella/charts/subscriber-proxy/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: subscriber-proxy-logconfig
  labels:
    app: subscriber-proxy
    chart: "subscriber-proxy-0.2.1"
    release: "aether-roc-umbrella"
    heritage: "Helm"
data:
  logging.yaml: |-
    loggers:
      root:
        level: info
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        stdout: {}
        type: stdout
