apiVersion: v1
kind: ConfigMap
metadata:
  name: onos-topo-config
  labels:
    app: onos-topo
    chart: "onos-topo-1.3.5"
    release: "aether-roc-umbrella"
    heritage: "Helm"
data:
  onos.yaml: ""
  logging.yaml: |2-

    loggers:
      root:
        level: info
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        stdout: {}
        type: stdout
