apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-roc-api-config
  labels:
    app: aether-roc-api
    chart: "aether-roc-api-1.7.12"
    release: "aether-roc-umbrella"
    heritage: "Helm"
data:
  logging.yaml: |-
    loggers:
      root:
        level: info
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        stdout: {}
        type: stdout
