apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-roc-umbrella-sdcore-adapter-v2-1-logconfig
  labels:
    app: aether-roc-umbrella-sdcore-adapter-v2-1
    chart: "sdcore-adapter-v2-1-2.1.3"
    release: "aether-roc-umbrella"
    heritage: "Helm"
data:
  logging.yaml: |-
    loggers:
      root:
        level: info
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        stdout: {}
        type: stdout
