apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-roc-umbrella-grafana-post-install
  labels:
    chart: "aether-roc-umbrella-2.1.29"
    release: "aether-roc-umbrella"
    heritage: "Helm"
data: {}
