apiVersion: v1
kind: Service
metadata:
  name: aether-roc-gui-v2-1
  labels:
    app: aether-roc-gui-v2-1
    chart: "aether-roc-gui-v2-1-2.1.15"
    release: "aether-roc-umbrella"
    heritage: "Helm"
    helm.sh/chart: aether-roc-gui-v2-1-2.1.15
    app.kubernetes.io/name: aether-roc-gui-v2-1
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  selector:
    name: aether-roc-gui-v2-1
    app: aether
    type: arg
    resource: aether-roc-gui-v2-1
    app.kubernetes.io/name: aether-roc-gui-v2-1
    app.kubernetes.io/instance: aether-roc-umbrella
  ports:
  - name: web
    port: 80
