apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sdcore-adapter
  labels:
    helm.sh/chart: sdcore-adapter-v2-1-2.1.3
    app.kubernetes.io/name: sdcore-adapter-v2-1
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/version: "v2.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sdcore-adapter-v2-1
      app.kubernetes.io/instance: aether-roc-umbrella
  endpoints:
  - port: prometheus
    path: /metrics
    scheme: HTTP
