apiVersion: v1
kind: Service
metadata:
  name: aether-roc-api
  labels:
    app: aether-roc-api
    chart: "aether-roc-api-1.7.12"
    release: "aether-roc-umbrella"
    heritage: "Helm"
    helm.sh/chart: aether-roc-api-1.7.12
    app.kubernetes.io/name: aether-roc-api
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/version: "v0.10.16"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    name: aether-roc-api
    app: aether
    type: api
    resource: aether-roc-api
    app.kubernetes.io/name: aether-roc-api
    app.kubernetes.io/instance: aether-roc-umbrella
  ports:
  - name: rest
    port: 8181
