apiVersion: v1
kind: Service
metadata:
  name: onos-config
  labels:
    app: onos-config
    chart: "onos-config-1.7.8"
    release: "aether-roc-umbrella"
    heritage: "Helm"
    helm.sh/chart: onos-config-1.7.8
    app.kubernetes.io/name: onos-config
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/version: "v0.10.36"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    name: onos-config
    app: onos
    type: config
    resource: onos-config
    app.kubernetes.io/name: onos-config
    app.kubernetes.io/instance: aether-roc-umbrella
  ports:
  - name: grpc
    port: 5150
  - name: registry
    port: 5151
