# Source: aether-roc-umbrella/charts/prom-label-proxy-amp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prom-label-proxy-amp
  labels:
    app: prom-label-proxy-amp
    chart: "prom-label-proxy-amp-0.1.2"
    release: "aether-roc-umbrella"
    heritage: "Helm"
    helm.sh/chart: prom-label-proxy-amp-0.1.2
    app.kubernetes.io/name: prom-label-proxy-amp
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/version: "v0.3.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    name: prom-label-proxy-amp
  ports:
  - name: http
    port: 8080
  - name: gnmi
    port: 5150
