apiVersion: v1
kind: Service
metadata:
  name: onos-topo
  labels:
    app: onos-topo
    chart: "onos-topo-1.3.5"
    release: "aether-roc-umbrella"
    heritage: "Helm"
    helm.sh/chart: onos-topo-1.3.5
    app.kubernetes.io/name: onos-topo
    app.kubernetes.io/instance: aether-roc-umbrella
    app.kubernetes.io/version: "v0.9.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    name: onos-topo
    app: onos
    type: topo
    resource: onos-topo
    app.kubernetes.io/name: onos-topo
    app.kubernetes.io/instance: aether-roc-umbrella
  ports:
  - name: grpc
    port: 5150
