# Source: sd-core/charts/5g-control-plane/templates/deployment-ausf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ausf
  namespace: default
  labels:
    release: sd-core
    app: ausf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ausf
subjects:
- kind: ServiceAccount
  name: ausf
  namespace: default
