# Source: sd-core/charts/5g-control-plane/templates/deployment-ausf.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ausf
  namespace: default
  labels:
    release: sd-core
    app: ausf
rules:
- apiGroups:
  - ""
  - extensions
  - batch
  - apps
  verbs:
  - get
  - list
  - patch
  resources:
  - statefulsets
  - daemonsets
  - jobs
  - pods
  - services
  - endpoints
  - configmaps
