# Source: sd-core/charts/5g-control-plane/templates/deployment-smf.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
  labels:
    release: sd-core
    app: smf
spec:
  replicas: 1
  #serviceName: smf-headless
  selector:
    matchLabels:
      release: sd-core
      app: smf
  template:
    metadata:
      labels:
        release: sd-core
        app: smf
      annotations:
        helm.sh/hook: pre-install
        helm.sh/hook-weight: "5"
        field.cattle.io/workloadMetrics: '[{"path":"/metrics","port":9089,"schema":"HTTP"}]'
    spec:
      serviceAccountName: smf
      initContainers:
      - name: wait-smf-module
        image: registry.opennetworking.org/docker.io/omecproject/pod-init:1.0.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup smf; do echo waiting for smf; sleep 4; done;']
      containers:
      - name: smf
        image: registry.opennetworking.org/docker.io/omecproject/5gc-smf:master-6451e24
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        command: ["/free5gc/script/smf-run.sh"]
        env:
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        - name: GRPC_TRACE
          value: "all"
        - name: GRPC_VERBOSITY
          value: "debug"
        - name: PFCP_PORT_UPF
          value: "8805"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MANAGED_BY_CONFIG_POD
          value: "true"
        volumeMounts:
        - name: run-script
          mountPath: /free5gc/script/smf-run.sh
          subPath: smf-run.sh
        - name: nf-config
          mountPath: /free5gc/uerouting
        - name: nf-config
          mountPath: /free5gc/config
      volumes:
      - name: run-script
        configMap:
          name: smf
          defaultMode: 493
      - name: nf-config
        configMap:
          name: smf
          defaultMode: 493
