# Source: sd-core/charts/5g-control-plane/templates/configmap-nssf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf
  labels:
    release: sd-core
    app: nssf
data:
  nssf-run.sh: |
    #!/bin/sh

    # Copyright 2020-present Open Networking Foundation
    #
    # SPDX-License-Identifier: Apache-2.0

    set -xe

    cd /free5gc

    cat config/nssfcfg.conf

    GOTRACEBACK=crash ./nssf/nssf -nssfcfg config/nssfcfg.conf
  nssfcfg.conf: |-
    configuration:
      nrfUri: http://nrf:29510
      nsiList:
      - nsiInformationList:
        - nrfId: http://nrf:29510/nnrf-nfm/v1/nf-instances
          nsiId: 22
        snssai:
          sd: "010203"
          sst: 1
      nssfName: NSSF
      sbi:
        bindingIPv4: 0.0.0.0
        port: 29531
        registerIPv4: nssf
        scheme: http
      serviceNameList:
      - nnssf-nsselection
      - nnssf-nssaiavailability
      supportedNssaiInPlmnList:
      - plmnId:
          mcc: "208"
          mnc: "93"
        supportedSnssaiList:
        - sd: "010203"
          sst: 1
      supportedPlmnList:
      - mcc: "208"
        mnc: "93"
    info:
      description: NSSF initial local configuration
      version: 1.0.0
    logger:
      AMF:
        ReportCaller: false
        debugLevel: info
      AUSF:
        ReportCaller: false
        debugLevel: info
      Aper:
        ReportCaller: false
        debugLevel: info
      CommonConsumerTest:
        ReportCaller: false
        debugLevel: info
      FSM:
        ReportCaller: false
        debugLevel: info
      MongoDBLibrary:
        ReportCaller: false
        debugLevel: info
      N3IWF:
        ReportCaller: false
        debugLevel: info
      NAS:
        ReportCaller: false
        debugLevel: info
      NGAP:
        ReportCaller: false
        debugLevel: info
      NRF:
        ReportCaller: false
        debugLevel: info
      NamfComm:
        ReportCaller: false
        debugLevel: info
      NamfEventExposure:
        ReportCaller: false
        debugLevel: info
      NsmfPDUSession:
        ReportCaller: false
        debugLevel: info
      NudrDataRepository:
        ReportCaller: false
        debugLevel: info
      OpenApi:
        ReportCaller: false
        debugLevel: info
      PCF:
        ReportCaller: false
        debugLevel: info
      PFCP:
        ReportCaller: false
        debugLevel: info
      PathUtil:
        ReportCaller: false
        debugLevel: info
      SMF:
        ReportCaller: false
        debugLevel: info
      UDM:
        ReportCaller: false
        debugLevel: info
      UDR:
        ReportCaller: false
        debugLevel: info
      WEBUI:
        ReportCaller: false
        debugLevel: info
