# Source: sd-core/charts/5g-control-plane/templates/deployment-udm.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  labels:
    release: sd-core
    app: udm
spec:
  replicas: 1
  #serviceName: udm-headless
  selector:
    matchLabels:
      release: sd-core
      app: udm
  template:
    metadata:
      labels:
        release: sd-core
        app: udm
    spec:
      serviceAccountName: udm
      initContainers:
      - name: wait-udm-module
        image: registry.opennetworking.org/docker.io/omecproject/pod-init:1.0.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup udm; do echo waiting for udm; sleep 4; done;']
      - name: wait-udr-module
        image: registry.opennetworking.org/docker.io/omecproject/pod-init:1.0.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup udr; do echo waiting for udr; sleep 4; done;']
      containers:
      - name: udm
        image: registry.opennetworking.org/docker.io/omecproject/5gc-udm:master-6956659
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        command: ["/free5gc/script/udm-run.sh"]
        env:
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        - name: GRPC_TRACE
          value: "all"
        - name: GRPC_VERBOSITY
          value: "debug"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MANAGED_BY_CONFIG_POD
          value: "true"
        volumeMounts:
        - name: run-script
          mountPath: /free5gc/script/udm-run.sh
          subPath: udm-run.sh
        - name: nf-config
          mountPath: /free5gc/config
      volumes:
      - name: run-script
        configMap:
          name: udm
          defaultMode: 493
      - name: nf-config
        configMap:
          name: udm
          defaultMode: 493
      - name: config-dir
        emptyDir: {}
