# Source: sd-core/charts/omec-user-plane/templates/service-upf.yaml
apiVersion: v1
kind: Service
metadata:
  name: upf
  labels:
    release: sd-core
    app: upf
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: upf
  ports:
  - name: pfcp
    protocol: UDP
    port: 8805
