# Source: sd-core/charts/5g-control-plane/templates/service-amf.yaml
apiVersion: v1
kind: Service
metadata:
  name: amf
  labels:
    release: sd-core
    app: amf
spec:
  type: ClusterIP
  externalIPs:
  - 192.168.10.120
  selector:
    release: sd-core
    app: amf
  ports:
  - name: prometheus-exporter
    port: 9089
    protocol: TCP
  - name: sbi
    port: 29518
    protocol: TCP
  - name: ngapp
    port: 38412
    protocol: SCTP
  - name: sctp-grpc
    port: 9000
    protocol: TCP
