# Source: sd-core/charts/omec-user-plane/templates/statefulset-upf.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: upf
  labels:
    release: sd-core
    app: upf
spec:
  replicas: 1
  serviceName: upf-headless
  selector:
    matchLabels:
      release: sd-core
      app: upf
  template:
    metadata:
      labels:
        release: sd-core
        app: upf
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "access-net", "interface": "access", "ips": ["192.168.252.3/24"] }, { "name": "core-net", "interface": "core", "ips": ["192.168.250.3/24"] } ]'
    spec:
      shareProcessNamespace: true
      imagePullSecrets:
      - name: aether.registry
      initContainers:
      - name: bess-init
        image: "omecproject/upf-epc-bess:master-5786085"
        imagePullPolicy: "IfNotPresent"
        command: ["sh", "-xec"]
        args:
        - ip route replace 10.60.1.0/24 via 192.168.252.1; ip route replace default via 192.168.250.1 metric 110; iptables -I OUTPUT -p icmp --icmp-type port-unreachable -j DROP;
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        resources:
          limits:
            cpu: 128m
            memory: 64Mi
          requests:
            cpu: 128m
            memory: 64Mi
      containers:
      - name: bessd
        image: "omecproject/upf-epc-bess:master-5786085"
        imagePullPolicy: "IfNotPresent"
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        stdin: true
        tty: true
        command: ["/bin/bash", "-xc"]
        args:
        - bessd -m 0 -f -grpc-url=0.0.0.0:10514
        lifecycle:
          postStart:
            exec:
              command: ["/etc/bess/conf/bessd-poststart.sh"]
        livenessProbe:
          tcpSocket:
            port: 10514
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
          limits:
        env:
        - name: CONF_FILE
          value: /etc/bess/conf/upf.json
        volumeMounts:
        - name: shared-app
          mountPath: /pod-share
        - name: configs
          mountPath: /etc/bess/conf
      - name: routectl
        image: "omecproject/upf-epc-bess:master-5786085"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        command: ["/opt/bess/bessctl/conf/route_control.py"]
        args:
        - -i
        - access
        - core
      - name: web
        image: "omecproject/upf-epc-bess:master-5786085"
        imagePullPolicy: "IfNotPresent"
        command: ["/bin/bash", "-xc", "bessctl http 0.0.0.0 8000"]
      - name: pfcp-agent
        image: "omecproject/upf-epc-pfcpiface:master-5786085"
        imagePullPolicy: "IfNotPresent"
        command: ["pfcpiface"]
        args:
        - -config
        - /tmp/conf/upf.json
        volumeMounts:
        - name: shared-app
          mountPath: /pod-share
        - name: configs
          mountPath: /tmp/conf
      - name: arping
        image: "registry.aetherproject.org/tools/busybox:stable"
        imagePullPolicy: "IfNotPresent"
        command: ["sh", "-xc"]
        args:
        - |
          while true; do
            # arping does not work - BESS graph is still disconnected
            #arping -c 2 -I access 192.168.252.1
            #arping -c 2 -I core 192.168.250.1
            ping -c 2 192.168.252.1
            ping -c 2 192.168.250.1
            sleep 10
          done
        resources:
          limits:
            cpu: 128m
            memory: 64Mi
          requests:
            cpu: 128m
            memory: 64Mi
      volumes:
      - name: configs
        configMap:
          name: upf
          defaultMode: 493
      - name: shared-app
        emptyDir: {}
