kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onos-operator-topo
  labels:
    app: onos-operator-topo
    chart: "topo-operator-0.5.4"
    release: "onos-operator"
    heritage: "Helm"
subjects:
- kind: ServiceAccount
  name: onos-operator-topo
  namespace: default
roleRef:
  kind: ClusterRole
  name: onos-operator-topo
  apiGroup: rbac.authorization.k8s.io
