apiVersion: v1
kind: ConfigMap
metadata:
  name: onos-operator-app-config
  labels:
    app: onos-operator-app
    chart: "app-operator-0.5.4"
    release: "onos-operator"
    heritage: "Helm"
data:
  logging.yaml: |-
    loggers:
      root:
        level: info
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        stdout: {}
        type: stdout
