# Source: crds/service.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: services.topo.onosproject.org
spec:
  group: topo.onosproject.org
  scope: Namespaced
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
    shortNames:
    - svc
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              selector:
                type: object
                properties:
                  matchLabels:
                    type: object
                    additionalProperties:
                      type: string
          status:
            type: object
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1","v1beta1"]
      clientConfig:
        service:
          name: serviceconversion
          namespace: kube-system
