apiVersion: v1
kind: Service
metadata:
  name: onos-operator-app
  labels:
    app: onos-operator-app
    chart: "app-operator-0.5.4"
    release: "onos-operator"
    heritage: "Helm"
spec:
  selector:
    name: onos-operator-app
  ports:
  - name: webhook
    port: 443
    targetPort: 443
