# Source: atomix-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomix-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: atomix-controller
  template:
    metadata:
      labels:
        name: atomix-controller
    spec:
      serviceAccountName: atomix-controller
      initContainers:
      - name: init-certs
        image: "atomix/atomix-controller-init-certs:v0.6.2"
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        env:
        - name: CONTROLLER_NAME
          value: atomix-controller
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config
          mountPath: /etc/atomix/config
          readOnly: true
        - name: certs
          mountPath: /etc/webhook/certs
      containers:
      - name: atomix-controller
        # Replace this with the built image name
        image: "atomix/atomix-controller:v0.6.2"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 5679
          name: control
        - containerPort: 443
          name: webhook-server
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/atomix-controller-ready
          initialDelaySeconds: 4
          periodSeconds: 10
          failureThreshold: 1
        env:
        - name: CONTROLLER_NAME
          value: atomix-controller
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEFAULT_BROKER_IMAGE
          value: "atomix/atomix-broker:v0.6.2"
        volumeMounts:
        - name: certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
        - name: config
          mountPath: /etc/atomix/config
          readOnly: true
      volumes:
      - name: certs
        emptyDir: {}
      - name: config
        configMap:
          name: atomix-controller-config
