# Source: atomix-controller/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: atomix-controller
  labels:
    name: atomix-controller
spec:
  selector:
    name: atomix-controller
  ports:
  - name: control
    port: 5679
  - name: webhook
    port: 443
    targetPort: 443
