# Source: sd-core/charts/5g-control-plane/templates/deployment-webui.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  labels:
    release: sd-core
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      release: sd-core
      app: webui
  template:
    metadata:
      labels:
        release: sd-core
        app: webui
    spec:
      serviceAccountName: webui
      initContainers:
      - name: wait-webui-module
        image: registry.opennetworking.org/docker.io/omecproject/pod-init:1.0.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup webui; do echo waiting for webui; sleep 4; done;']
      containers:
      - name: webui
        image: registry.opennetworking.org/docker.io/omecproject/5gc-webui:master-fec9bfc
        env:
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        - name: GRPC_TRACE
          value: "all"
        - name: GRPC_VERBOSITY
          value: "debug"
        - name: CONFIGPOD_DEPLOYMENT
          value: "5G"
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        command: ["/free5gc/script/webui-run.sh"]
        volumeMounts:
        - name: run-script
          mountPath: /free5gc/script/webui-run.sh
          subPath: webui-run.sh
        - name: nf-config
          mountPath: /free5gc/config
      volumes:
      - name: run-script
        configMap:
          name: webui
          defaultMode: 493
      - name: nf-config
        configMap:
          name: webui
          defaultMode: 493
