# Source: sd-core/charts/5g-control-plane/templates/deployment-nrf.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf
  labels:
    release: sd-core
    app: nrf
spec:
  replicas: 1
  #serviceName: nrf-headless
  selector:
    matchLabels:
      release: sd-core
      app: nrf
  template:
    metadata:
      labels:
        release: sd-core
        app: nrf
    spec:
      serviceAccountName: nrf
      containers:
      - name: nrf
        image: registry.opennetworking.org/docker.io/omecproject/5gc-nrf:master-5200cf8
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        command: ["/free5gc/script/nrf-run.sh"]
        env:
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        - name: GRPC_TRACE
          value: "all"
        - name: GRPC_VERBOSITY
          value: "debug"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MANAGED_BY_CONFIG_POD
          value: "true"
        volumeMounts:
        - name: run-script
          mountPath: /free5gc/script/nrf-run.sh
          subPath: nrf-run.sh
        - name: nf-config
          mountPath: /free5gc/config
      volumes:
      - name: run-script
        configMap:
          name: nrf
          defaultMode: 493
      - name: nf-config
        configMap:
          name: nrf
          defaultMode: 493
