# Source: sd-core/charts/omec-user-plane/templates/networks.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: access-net
  namespace: default
spec:
  config: '{ "cniVersion": "0.3.1", "type": "macvlan", "master": "enp1s0", "ipam": { "type": "static" }, "capabilities": { "mac": true} }'
