# Source: sd-core/charts/5g-control-plane/templates/service-nssf.yaml
apiVersion: v1
kind: Service
metadata:
  name: nssf
  labels:
    release: sd-core
    app: nssf
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: nssf
  ports:
  - name: sbi
    port: 29531
    protocol: TCP
