# Source: sd-core/charts/omec-user-plane/templates/service-upf.yaml
apiVersion: v1
kind: Service
metadata:
  name: upf-http
  labels:
    release: sd-core
    app: upf
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: upf
  ports:
  - name: bess-web
    protocol: TCP
    port: 8000
  - name: prometheus-exporter
    protocol: TCP
    port: 8080
