# Source: sd-core/charts/omec-sub-provision/templates/service-simapp.yaml
apiVersion: v1
kind: Service
metadata:
  name: simapp
  labels:
    release: sd-core
    app: simapp
spec:
  type: ClusterIP
  selector:
    release: sd-core
    app: simapp
  ports:
  - name: prometheus-exporter
    port: 9089
    protocol: TCP
  - name: config-exporter
    port: 8080
    protocol: TCP
