# Source: atomix-raft-storage/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: atomix-raft-storage-controller
subjects:
- kind: ServiceAccount
  name: atomix-raft-storage-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: atomix-raft-storage-controller
  apiGroup: rbac.authorization.k8s.io
