# Source: onos-operator/charts/app-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onos-operator-app
  namespace: kube-system
  labels:
    app: onos-operator-app
    chart: "app-operator-0.5.1"
    release: "onos-operator"
    heritage: "Helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onos-operator-app
  template:
    metadata:
      labels:
        name: onos-operator-app
        release: onos-operator
        app.kubernetes.io/name: "onos-operator-app"
        app.kubernetes.io/version: "v0.5.0"
        app.kubernetes.io/part-of: "onos-operator"
        helm.sh/chart: "app-operator-0.5.1"
    spec:
      serviceAccountName: onos-operator-app
      initContainers:
      - name: init-certs
        image: "onosproject/config-operator-init:v0.5.0"
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        env:
        - name: CONTROLLER_NAME
          value: onos-operator-app
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTROLLER_SCOPE
          value: cluster
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GLOBAL_IMAGE_REGISTRY
          value: ""
        volumeMounts:
        - name: config
          mountPath: /etc/onos/config
          readOnly: true
        - name: plugins
          mountPath: /etc/onos/plugins
        - name: certs
          mountPath: /etc/webhook/certs
      containers:
      - name: controller
        image: "onosproject/app-operator:v0.5.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 60000
          name: metrics
        - containerPort: 443
          name: webhook-server
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/onos-operator-ready
          initialDelaySeconds: 4
          periodSeconds: 10
          failureThreshold: 1
        env:
        - name: CONTROLLER_NAME
          value: onos-operator-app
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTROLLER_SCOPE
          value: cluster
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GLOBAL_IMAGE_REGISTRY
          value: ""
        volumeMounts:
        - name: config
          mountPath: /etc/onos/config
          readOnly: true
        - name: plugins
          mountPath: /etc/onos/plugins
        - name: certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: onos-operator-app-config
      - name: certs
        emptyDir: {}
      - name: plugins
        emptyDir: {}
